backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
    - name: "cakes"
    label: "Theme Cakes"
    folder: "_cakes"
    create: true
    slug: "{{slug}}"
    fields:
            - {label: "Cake Name", name: "title", widget: "string"}
            - {label: "Cake Photo", name: "image", widget: "image"}
            - {label: "WhatsApp Message", name: "whatsapp_text", widget: "string", default: "I want this cake"}
